name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RESOURCE_GROUP: SomeDemo
  WEBAPP_NAME: SomeDemoFromColin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore dependencies
        run: dotnet restore SomeDemo
        
      - name: Build
        run: dotnet build SomeDemo --no-restore
        
      - name: Publish
        run: dotnet publish SomeDemo/SomeDemo.csproj -c Release -o SomeDemo/output
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: website
          path: SomeDemo/output/**
          if-no-files-found: error
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: IaC
          path: ./IaC/*.*

 IaC:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: IaC
          path: ./IaC

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            az deployment group create --resource-group ${{env.RESOURCE_GROUP}} --template-file ./IaC/webApp.bicep --parameters webappname=${{env.WEBAPP_NAME}}
